### PR TITLE
fix: properly bind singleton

### LINKED ISSUE #290: PHP Warnings while resolving 'Facade\Ignition\DumpRecorder\MultiDumpHandler'
👋 While working on debugging https://github.com/psalm/psalm-plugin-laravel/issues/94 , I have noticed that I receive php errors while attempting to resolve `Facade\\Ignition\\DumpRecorder\\MultiDumpHandler` from the container.

Laravel v7.19.1
```
composer show | grep -E 'ignition|laravel'

barryvdh/laravel-ide-helper           v2.7.0    Laravel IDE Helper, generates correct PHPDocs for all Facade cl...
facade/ignition                       2.3.1     A beautiful error page for Laravel applications.
facade/ignition-contracts             1.0.0     Solution contracts for Ignition
fruitcake/laravel-cors                v1.0.6    Adds CORS (Cross-Origin Resource Sharing) headers support in yo...
laravel/framework                     v7.19.1   The Laravel Framework.
laravel/tinker                        v2.4.1    Powerful REPL for the Laravel framework.
psalm/plugin-laravel                  v1.3.1    A Laravel plugin for Psalm


php artisan tinker

Psy Shell v0.10.4 (PHP 7.4.7 — cli) by Justin Hileman
>>> app()->make('Facade\Ignition\DumpRecorder\MultiDumpHandler');
PHP Warning:  Illegal offset type in isset or empty in /Users/fiachra/repos/repro-psalm-laravel-undefined-index/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1159
```

### PR DESCRIPTION
**Pull request by mr-feek**
fixes #290 

👋 You may want to consider bringing in psalm to help ya out!

The typehint for `Container::singleton` is `@param  \Closure|string|null  $concrete` https://github.com/laravel/framework/blob/7.x/src/Illuminate/Container/Container.php#L352

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

File: src/DumpRecorder/DumpRecorder.php [hunk 1]
```diff
@@ -26,7 +26,9 @@ public function register(): self
     {
         $multiDumpHandler = new MultiDumpHandler();
 
-        $this->app->singleton(MultiDumpHandler::class, $multiDumpHandler);
+        $this->app->singleton(MultiDumpHandler::class, function () use ($multiDumpHandler) {
+            return $multiDumpHandler;
+        });
```
Comment (mfn) [inline src/DumpRecorder/DumpRecorder.php:31]: Couldn't this just be ?
```php
$this->app->instance(MultiDumpHandler::class, $multiDumpHandler);
```

This would be also more clearly convey the intend here. The closure factory looks redundant.

Comment (mr-feek) [reply src/DumpRecorder/DumpRecorder.php:31]: yeah, i always forget about `instance` -- both should have the same effect
